# file: .github/workflows/publish.yml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - main
    paths:
      - 'src/Plugin.Maui.ML/Plugin.Maui.ML.csproj'
      - '.github/workflows/publish.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - 'src/Plugin.Maui.ML/Plugin.Maui.ML.csproj'
      - '.github/workflows/publish.yml'
  release:
    types: [ published ]

env:
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

permissions: {}

jobs:
  create_nuget:
    runs-on: windows-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          show-progress: false
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: 'global.json'
      
      - name: Install MAUI workloads
        run: dotnet workload install maui-android maui-ios maui-maccatalyst

      - name: Determine Version
        id: minver
        run: |
            dotnet tool install --global minver-cli
            git fetch --tags
            git tag
            $version = minver --auto-increment minor --build-metadata build --verbosity trace
            echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV
            echo "version=$version" >> $env:GITHUB_OUTPUT

      - run: dotnet pack src/Plugin.Maui.ML/Plugin.Maui.ML.csproj --configuration Release --output ${{ env.NuGetDirectory }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:Version=${{ env.PACKAGE_VERSION }}
      
      - name: Prepare Artifacts
        run: |
          mkdir -p ${{ env.NuGetDirectory }}/artifacts
          cp ${{ env.NuGetDirectory }}/*.nupkg ${{ env.NuGetDirectory }}/artifacts
          cp ${{ env.NuGetDirectory }}/*.snupkg ${{ env.NuGetDirectory }}/artifacts
      
      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: |
            ${{ env.NuGetDirectory }}/artifacts/*.nupkg
            ${{ env.NuGetDirectory }}/artifacts/*.snupkg

  run_tests:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          show-progress: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: 'global.json'
      - name: Run tests
        run: dotnet test tests/Plugin.Maui.ML.Tests/Plugin.Maui.ML.Tests.csproj --configuration Release --filter 'FullyQualifiedName!~TestBase'

  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ create_nuget, run_tests ]
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          }